spring:
  application:
    name: moti-eureka-server
server:
  port: 8761

eureka:
  client:
    # eureka ?????? ??? ???? ??(?? ????? peering ??? ?? ??? ??)
    register-with-eureka: false
    # ?????? ?? ??? ???? ?? true ?? ? Eureka Server ?? ?? ?????? ??? ???
    fetch-registry: false
