spring:
  application:
    name: moti-eureka-server
server:
  port: 8761

eureka:
  client:
    # 이 애플리케이션을 Eureka 서버에 등록하지 않음 (보통 Config Server, Discovery Server에서 사용)
    register-with-eureka: false
    # 다른 서비스들의 레지스트리 정보를 가져오지 않음 (서비스 간 호출이 필요 없는 경우 false)
    fetch-registry: false
