services:
  eureka-server:
    image: koboolean/moti-eureka-server
    container_name: moti-eureka-server
    ports:
      - "8761:8761"
    networks:
      - moti
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: always

  config-server:
    image: koboolean/moti-config-server
    container_name: moti-config-server
    ports:
      - "8888:8888"
    networks:
      - moti
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: always

  moti-db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: local_moti_postgres_db
      POSTGRES_DB: moti
      POSTGRES_USER: moti
    ports:
      - "5432:5432"
    volumes:
      - ./volume/db:/var/lib/postgresql/data
    container_name: moti-db

  gateway-service:
    image: koboolean/moti-gateway-service
    container_name: moti-gateway-service
    ports:
      - "80:80"
    networks:
      - moti
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: always

networks:
  moti:
    driver: bridge
